#!/usr/bin/env python3
"""
Generate deterministic level seeds for policy training, OOD training, and evaluation.

This script creates reproducible seed sets that can be used with the procgen-afh
fork's ordered level seeds feature (level_seeds parameter).

Usage:
    python generate_level_seeds.py --policy-train 10000 --ood-train 5000 --eval 1000 -o seeds.json
    python generate_level_seeds.py --policy-train 50000 --ood-train 10000 --eval 2000 --base-seed 42

The generated seeds are:
- Deterministic: Same base seed always produces same seed sets
- Non-overlapping: Each phase gets unique seeds
- Shuffled within phase: Seeds are randomly ordered but reproducibly so
"""

import argparse
import json
from pathlib import Path
from typing import Dict, List

import numpy as np


def generate_seeds(
    num_policy_train: int,
    num_ood_train: int,
    num_eval: int,
    base_seed: int = 0,
) -> Dict[str, List[int]]:
    """
    Generate deterministic, non-overlapping seed sets for each training phase.

    The seeds are generated by:
    1. Creating a large pool of sequential integers
    2. Shuffling them deterministically using the base_seed
    3. Splitting into non-overlapping chunks for each phase

    Args:
        num_policy_train: Number of seeds for policy training
        num_ood_train: Number of seeds for OOD detector training
        num_eval: Number of seeds for evaluation
        base_seed: Base random seed for reproducible generation

    Returns:
        Dictionary with keys 'policy_train', 'ood_train', 'eval' containing seed lists
    """
    total_seeds = num_policy_train + num_ood_train + num_eval

    # Create RNG with base seed for reproducibility
    rng = np.random.default_rng(base_seed)

    # Generate a pool of unique seeds and shuffle them
    # We use a large range to avoid any potential collisions
    seed_pool = np.arange(total_seeds)
    rng.shuffle(seed_pool)

    # Split into non-overlapping sets
    policy_end = num_policy_train
    ood_end = policy_end + num_ood_train

    seeds = {
        "policy_train": seed_pool[:policy_end].tolist(),
        "ood_train": seed_pool[policy_end:ood_end].tolist(),
        "eval": seed_pool[ood_end:].tolist(),
    }

    return seeds


def save_seeds(seeds: Dict[str, List[int]], output_path: Path, base_seed: int) -> None:
    """
    Save seeds to a JSON file with metadata.

    Args:
        seeds: Dictionary of seed lists
        output_path: Path to save the JSON file
        base_seed: The base seed used for generation (for documentation)
    """
    output_data = {
        "metadata": {
            "base_seed": base_seed,
            "num_policy_train": len(seeds["policy_train"]),
            "num_ood_train": len(seeds["ood_train"]),
            "num_eval": len(seeds["eval"]),
            "description": (
                "Deterministic level seeds for procgen environments. "
                "Use with level_seeds parameter in ProcgenGym3Env."
            ),
        },
        "seeds": seeds,
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        json.dump(output_data, f, indent=2)

    print(f"Saved seeds to {output_path}")
    print(f"  - Policy training: {len(seeds['policy_train'])} seeds")
    print(f"  - OOD training:    {len(seeds['ood_train'])} seeds")
    print(f"  - Evaluation:      {len(seeds['eval'])} seeds")


def load_seeds(input_path: Path) -> Dict[str, List[int]]:
    """
    Load seeds from a JSON file.

    Args:
        input_path: Path to the JSON file

    Returns:
        Dictionary with seed lists for each phase
    """
    with open(input_path) as f:
        data = json.load(f)

    return data["seeds"]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate deterministic level seeds for policy training, OOD training, and evaluation.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate seeds with default counts
  python generate_level_seeds.py -o seeds/default.json

  # Generate custom seed counts
  python generate_level_seeds.py --policy-train 50000 --ood-train 10000 --eval 5000 -o seeds/large.json

  # Use a specific base seed for reproducibility
  python generate_level_seeds.py --base-seed 42 -o seeds/seed42.json

The generated JSON can be loaded and used with procgen:

  from generate_level_seeds import load_seeds
  from procgen import ProcgenGym3Env

  seeds = load_seeds("seeds.json")
  env = ProcgenGym3Env(num=4, env_name="coinrun", level_seeds=seeds["eval"])
        """,
    )

    parser.add_argument(
        "--policy-train",
        type=int,
        default=10000,
        help="Number of seeds for policy training (default: 10000)",
    )
    parser.add_argument(
        "--ood-train",
        type=int,
        default=5000,
        help="Number of seeds for OOD detector training (default: 5000)",
    )
    parser.add_argument(
        "--eval",
        type=int,
        default=1000,
        help="Number of seeds for evaluation (default: 1000)",
    )
    parser.add_argument(
        "--base-seed",
        type=int,
        default=0,
        help="Base random seed for deterministic generation (default: 0)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("seeds/level_seeds.json"),
        help="Output file path (default: seeds/level_seeds.json)",
    )

    args = parser.parse_args()

    # Validate arguments
    if args.policy_train < 0 or args.ood_train < 0 or args.eval < 0:
        parser.error("Seed counts must be non-negative")

    if args.policy_train + args.ood_train + args.eval == 0:
        parser.error("At least one phase must have seeds")

    # Generate and save seeds
    seeds = generate_seeds(
        num_policy_train=args.policy_train,
        num_ood_train=args.ood_train,
        num_eval=args.eval,
        base_seed=args.base_seed,
    )

    save_seeds(seeds, args.output, args.base_seed)


if __name__ == "__main__":
    main()

