paper_workflows:
  chai:
    checkpoint_base: /nas/ucb/czempin/data/goal-misgen/policy/icml
    seeds_base: /nas/ucb/czempin/data/goal-misgen/seeds/icml
    svdd_base: /nas/ucb/czempin/data/goal-misgen/trained_svdd
    log_base: /nas/ucb/czempin/data/goal-misgen/slurm-logs
  snoopy:
    checkpoint_base: /scr/pavel/data/goal-misgen/policy/icml
    seeds_base: /scr/pavel/data/goal-misgen/seeds/icml
    svdd_base: /scr/pavel/data/goal-misgen/trained_svdd
    log_base: /scr/pavel/data/goal-misgen/slurm-logs

strong_reval:
  server1:
    checkpoint_base: /data/goal-misgen/policy/icml
    evals_base: /data/goal-misgen/experiments/evals
  server2:
    checkpoint_base: /data2/goal-misgen/policy/icml
    evals_base: /data2/goal-misgen/experiments/evals
