# General settings
general:
    benchmark: 'procgen'
    algorithm: 'threshold'
    seed: 1

# Wandb settings
wandb:
    project: 'yrc-01'


# Evaluation settings
evaluation:
    num_bins: 20
    afhp_metric: 'level_afhp'
    video_episodes_to_collect: 16
    video_filter: ['all']

# Inherit all settings from common.yaml
environment: 
    common:
        env_name: 'coinrun'
        normalize_rew: False
        num_envs: 8
        num_threads: 8
        use_backgrounds: True
        use_monochrome_assets: False
        restrict_themes: False
    train:
        distribution_mode: 'hard'
        seed: 0
        start_level: 0
        num_levels: 100000
        random_percent: 0
    val_sim:
        distribution_mode: 'hard'
        seed: 100000
        start_level: 100000
        num_levels: 256
        random_percent: 50
    val_true:
        distribution_mode: 'hard'
        seed: 200000
        start_level: 200000
        num_levels: 256
        random_percent: 50
    test:
        distribution_mode: 'hard'
        seed: 300000
        start_level: 300000
        num_levels: 5120
        random_percent: 50
coord_env: null
coord_policy:
    cls: ThresholdPolicy
    feature_type: 'obs'
    collect_data_agent: 'weak'
    metric: 'max_prob'
algorithm: null
