# General settings
general:
    benchmark: 'procgen'
    algorithm: 'lightning_ae'
    seed: 1

# Wandb settings
wandb:
    project: 'yrc-01'


# Evaluation settings
evaluation:
    procgen:
        test_episodes: 5000

eval:
    coverage_fraction: 0.05

# Environment settings - inherit from common.yaml and override env_name
environment:
    common:
        env_name: 'coinrun_aisc'

# Inherit other settings from common.yaml
coord_env: null
coord_policy: null
algorithm: null
            
# File settings
file_name: 'trained.pt'
